Improve anyhow error handling
Print all the causes with {:#} formatter and replace
.unwrap() with ?.

When `cargo bolero test` is run, previously the error due to missing rustup was
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }'

Now the error is:
  error: failed to determine nightly toolchain version: No such file or directory (os error 2)

This way it is easier for the user to determine that nightly toolchain is used
and pass `--sanitizer NONE` to switch away from the nightly toolchain or
install the missing toolchain.