implement a generator based on Arbitrary for compatibility (#108)
* implement a generator based on Arbitrary for compatibility

* make the arbitrary feature opt-in

* hoist generation from a byte slice into Driver

* also implement with_arbitrary

* avoid being too slow when the len range is too wide in forced mode

* fix kani gen_from_bytes implementation

* keep msrv as it was

* add unit tests for arbitrary in makefile

* bump msrv for tests to pass

cargo doesn't think of taking old arbitrary versions and otherwise fails with
error: package `arbitrary v1.2.3` cannot be built because it requires rustc 1.63.0 or newer, while the currently active rustc version is 1.57.0

* do not oom trying to allocate big lots of memory

* do not even try to allocate too much at once, for asan

* handle clippy lints

* cargo fmt

* Undo cargo lints change

* Revert "bump msrv for tests to pass"

This reverts commit 6d55ef6eb9856023d0a7546e6fc6d1efedb5a649.

* Make CI work properly with two different MSRVs

* Set MSRV in clippy config

* Fix syntax in makefile

* Check version of rustc rather than cargo

* Move condition to github action

* Use matrix exclude

* fix typo

Co-authored-by: Cameron Bytheway <bytheway.cameron@gmail.com>

---------

Co-authored-by: Cameron Bytheway <bytheway.cameron@gmail.com>